#!/usr/bin/env zsh

export DOTFILES="$HOME/dotfiles-2"

export TERMINAL=/usr/bin/urxvt
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export LESS='-R --use-color -Ddg$DuY$DE+r$DP+c$DS+kY'

export XDG_CONFIG_HOME=$HOME/.config

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=1000000
export SAVEHIST=1000000

export en="--exclude-dir=node_modules"
export eb="--exclude-dir=build"
export ijk='--include=*.kt --include=*.java'

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export CHROME_BIN=/usr/bin/chromium

export PATH=$HOME/bin:$PATH
export PATH=$JAVA_HOME:$PATH
export PATH=~/.npm-global/bin:$PATH

export LS_COLORS="di=01;32:ex=00;34:ln=00;35"
export LS_COLORS="$LS_COLORS:*.zip=00;37:*.war=00;37"

#export KUBECONFIG=$HOME/.kube/config
export KUBECONFIG=$HOME/.kube/fe-gitlab-config
export KUBECONFIG=$KUBECONFIG:$HOME/.kube/integration-cluster-config
export KUBECONFIG=$KUBECONFIG:$HOME/.kube/kind-kind-config

export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
export PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable"

export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
